version: "3.8"

services:
  dev-api:
    build: .
    container_name: dev-api
    hostname: dev-api
    cap_add:
      - SYS_TIME
    ports:
      - "4180:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env